name: Deploy
on:
  push:
    branches:
      - main
jobs:
  node_setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v3
        with:
            node-version: 18
            cache: 'yarn'
  update_env:
    runs-on: ubuntu-latest
    needs: node_setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Substitute secrets in .env.template
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          OAUTH_REDIRECT_URL: ${{ secrets.OAUTH_REDIRECT_URL }}
          API_KEY: ${{ secrets.API_KEY }}
          CUSTOMER_ID: ${{ secrets.CUSTOMER_ID }}
          GOOGLE_MAP_TOKEN: ${{ secrets.GOOGLE_MAP_TOKEN }}
          DEVELOPER_TOKEN: ${{ secrets.DEVELOPER_TOKEN }}
          META_PAGE_ID: ${{ secrets.META_PAGE_ID }}
          META_ACCOUNT_ID: ${{ secrets.META_ACCOUNT_ID }}
          META_ACCESS_TOKEN: ${{ secrets.META_ACCESS_TOKEN }}
        run: envsubst < .env.template > .env
  build:
    runs-on: ubuntu-latest
    needs: [update_env, node_setup]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: false
          tags: user/server:latest
  deploy:
    runs-on: ubuntu-latest
    needs: [update_env, build, node_setup]
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            sudo docker pull user/server:latest
            sudo docker stop server || true
            sudo docker rm server || true
            sudo docker run -d --name server -p 5000:5000 user/app:latest