name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_REMOTE_ADDRESS }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          script: |
            sudo rm -rf tg_web_app
            sudo gh repo clone Monitozation/tg_web_app
            sudo cd tg_web_app
            sudo docker stop ${{ secrets.DOCKER_REPO_NAME }} || true
            sudo docker rm ${{ secrets.DOCKER_REPO_NAME }} || true
            touch .env
            echo "WEB_APP_URL=${{ secrets.WEB_APP_URL }}" >> .env
            echo "GOOGLE_GECOCODING_TOKEN=${{ secrets.GOOGLE_GECOCODING_TOKEN }}" >> .env
            echo "API_URL=${{ secrets.API_URL }}" >> .env
            echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            sudo docker build -t ${{ secrets.DOCKER_REPO_NAME }} .
            sudo docker run -d --name ${{ secrets.DOCKER_REPO_NAME }} --network proxy-network -p 5000:5000 ${{ secrets.DOCKER_REPO_NAME }}
      
